# This workflow automatically builds and deploys the Cloud Run service
# when a change is pushed to the 'main' branch.

name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

env:
  PROJECT_ID: hage-pta # Replace with your GCP Project ID
  SERVICE_NAME: pta-analytics-job # The name of your Cloud Run service
  REGION: us-central1 # The region of your Cloud Run service

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2 # Action to authenticate with GCP
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }} # Use the GitHub secret for credentials

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2 # Action to set up gcloud CLI
        with:
          project_id: ${{ env.PROJECT_ID }} # Use the project ID from environment variables

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 8080 \
            --set-secrets=/etc/secrets/credentials.json=volunteer_analytics:latest \
            --project=${{ env.PROJECT_ID }}
        # This command will:
        # 1. Trigger Cloud Build to build your Docker image from the Dockerfile in '.'
        # 2. Push the image to Google Artifact Registry.
        # 3. Deploy the new image to your Cloud Run service.
        # 4. Mount the Secret Manager secret as a file at the correct path.
